<#
.SYNOPSIS
    Pick the MinerU local backend based on GPU availability (Windows host dev).

.DESCRIPTION
    Mirror of mineru-autoselect.sh. Detects an NVIDIA GPU and writes a generated
    env fragment (sampai/docker/mineru.generated.env) consumed by the `mineru`
    compose service and the LightRAG server:
      - NVIDIA GPU present -> hybrid-auto-engine + image analysis, GPU overlay
      - no GPU             -> CPU `pipeline` backend, no overlay

    Returns the compose -f arguments on stdout so a caller can splat them:
        $files = (& mineru-autoselect.ps1).Trim() -split ' '
        docker compose @files up -d

    Detection order: nvidia-smi -> docker nvidia runtime.
#>
[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'
$DockerDir = Split-Path -Parent $PSScriptRoot
$EnvOut       = Join-Path $DockerDir 'mineru.generated.env'
$GpuOverlay   = Join-Path $DockerDir 'docker-compose.mineru-gpu.yml'
$BaseCompose  = Join-Path $DockerDir 'docker-compose.yml'

function Test-NvidiaGpu {
    $smi = Get-Command nvidia-smi -ErrorAction SilentlyContinue
    if ($smi) {
        try { & nvidia-smi -L *> $null; if ($LASTEXITCODE -eq 0) { return $true } } catch {}
    }
    $docker = Get-Command docker -ErrorAction SilentlyContinue
    if ($docker) {
        try {
            $info = & docker info 2>$null | Out-String
            if ($info -match '(?i)nvidia') { return $true }
        } catch {}
    }
    return $false
}

if (Test-NvidiaGpu) {
    $Backend = 'hybrid-auto-engine'; $ImageAnalysis = 'true';  $Mode = 'GPU'
    $ComposeFiles = "-f `"$BaseCompose`" -f `"$GpuOverlay`""
} else {
    $Backend = 'pipeline';           $ImageAnalysis = 'false'; $Mode = 'CPU'
    $ComposeFiles = "-f `"$BaseCompose`""
}

@"
# AUTO-GENERATED by mineru-autoselect.ps1 - do not edit by hand.
# Detected: $Mode
MINERU_API_MODE=local
MINERU_LOCAL_BACKEND=$Backend
MINERU_LOCAL_IMAGE_ANALYSIS=$ImageAnalysis
"@ | Out-File -FilePath $EnvOut -Encoding utf8

Write-Host "[mineru-autoselect] $Mode detected -> backend=$Backend image_analysis=$ImageAnalysis" -ForegroundColor Cyan
Write-Host "[mineru-autoselect] wrote $EnvOut" -ForegroundColor Cyan

# Emit compose -f args on stdout for the caller.
$ComposeFiles
