#!/usr/bin/env bash
# mineru-autoselect.sh — pick the MinerU local backend based on GPU availability.
#
# Writes a generated env fragment (sampai/docker/mineru.generated.env) that the
# `mineru` compose service and the LightRAG server both read, and prints the
# compose overlay flag to use:
#   - NVIDIA GPU present  -> hybrid-auto-engine + image analysis, GPU overlay
#   - no GPU              -> CPU `pipeline` backend, no overlay
#
# Usage:
#   ./mineru-autoselect.sh                # detect + write env fragment
#   eval "$(./mineru-autoselect.sh --print-compose)"   # also echo COMPOSE_FILES for the caller
#
# Detection order: nvidia-smi -> docker nvidia runtime -> /proc/driver/nvidia.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOCKER_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_OUT="$DOCKER_DIR/mineru.generated.env"
GPU_OVERLAY="$DOCKER_DIR/docker-compose.mineru-gpu.yml"
BASE_COMPOSE="$DOCKER_DIR/docker-compose.yml"

has_gpu() {
  if command -v nvidia-smi >/dev/null 2>&1 && nvidia-smi -L >/dev/null 2>&1; then
    return 0
  fi
  if command -v docker >/dev/null 2>&1 && docker info 2>/dev/null | grep -qiE 'Runtimes:.*nvidia|nvidia'; then
    return 0
  fi
  if [ -e /proc/driver/nvidia/version ]; then
    return 0
  fi
  return 1
}

if has_gpu; then
  BACKEND="hybrid-auto-engine"
  IMAGE_ANALYSIS="true"
  MODE="GPU"
  COMPOSE_FILES="-f $BASE_COMPOSE -f $GPU_OVERLAY"
else
  BACKEND="pipeline"
  IMAGE_ANALYSIS="false"
  MODE="CPU"
  COMPOSE_FILES="-f $BASE_COMPOSE"
fi

cat > "$ENV_OUT" <<EOF
# AUTO-GENERATED by mineru-autoselect.sh — do not edit by hand.
# Detected: $MODE
MINERU_API_MODE=local
MINERU_LOCAL_BACKEND=$BACKEND
MINERU_LOCAL_IMAGE_ANALYSIS=$IMAGE_ANALYSIS
EOF

echo "[mineru-autoselect] $MODE detected -> backend=$BACKEND image_analysis=$IMAGE_ANALYSIS" >&2
echo "[mineru-autoselect] wrote $ENV_OUT" >&2

if [ "${1:-}" = "--print-compose" ]; then
  # Emit a shell-evalable assignment so callers can do: eval "$(... --print-compose)"
  echo "COMPOSE_FILES='$COMPOSE_FILES'"
fi
