"""baseline schema

Revision ID: f7b90dc364e3
Revises: 
Create Date: 2026-06-08 20:19:45.062547
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f7b90dc364e3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('classrooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('code', sa.String(length=12), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_classrooms_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_classrooms')),
    sa.UniqueConstraint('owner_id', 'name', name='uq_classrooms_owner_name')
    )
    op.create_index(op.f('ix_classrooms_code'), 'classrooms', ['code'], unique=True)
    op.create_index(op.f('ix_classrooms_name'), 'classrooms', ['name'], unique=False)
    op.create_index(op.f('ix_classrooms_owner_id'), 'classrooms', ['owner_id'], unique=False)
    op.create_table('announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('classroom_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], name=op.f('fk_announcements_classroom_id_classrooms'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_announcements_created_by_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_announcements'))
    )
    op.create_index('ix_announcement_classroom_id', 'announcements', ['classroom_id'], unique=False)
    op.create_index('ix_announcement_created_at', 'announcements', ['created_at'], unique=False)
    op.create_table('classroom_members',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('classroom_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], name=op.f('fk_classroom_members_classroom_id_classrooms'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_classroom_members_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'classroom_id', name=op.f('pk_classroom_members'))
    )
    op.create_table('folders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('classroom_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], name=op.f('fk_folders_classroom_id_classrooms'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_folders'))
    )
    op.create_index(op.f('ix_folders_classroom_id'), 'folders', ['classroom_id'], unique=False)
    op.create_table('announcement_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('announcement_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcements.id'], name=op.f('fk_announcement_comments_announcement_id_announcements'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_announcement_comments_created_by_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_announcement_comments'))
    )
    op.create_index('ix_comment_announcement_id', 'announcement_comments', ['announcement_id'], unique=False)
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('file_key', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('processing_status', sa.Enum('pending', 'processing', 'completed', 'failed', name='processingstatus'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('folder_id', sa.Integer(), nullable=False),
    sa.Column('rag_doc_id', sa.String(length=512), nullable=True),
    sa.Column('track_id', sa.String(length=255), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], name=op.f('fk_files_folder_id_folders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_files'))
    )
    op.create_index(op.f('ix_files_folder_id'), 'files', ['folder_id'], unique=False)
    op.create_index(op.f('ix_files_rag_doc_id'), 'files', ['rag_doc_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', 'system', name='messagerole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_metadata', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], name=op.f('fk_chat_messages_file_id_files'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_chat_messages_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_messages'))
    )
    op.create_index(op.f('ix_chat_messages_file_id'), 'chat_messages', ['file_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_user_id'), 'chat_messages', ['user_id'], unique=False)
    op.create_table('flashcard_decks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'generating', 'ready', 'failed', name='flashcarddeckstatus'), nullable=False),
    sa.Column('card_count', sa.Integer(), nullable=True),
    sa.Column('generation_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('ready_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], name=op.f('fk_flashcard_decks_file_id_files'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_flashcard_decks_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_flashcard_decks'))
    )
    op.create_index('ix_deck_status', 'flashcard_decks', ['status'], unique=False)
    op.create_index('ix_deck_user_file', 'flashcard_decks', ['user_id', 'file_id'], unique=False)
    op.create_table('group_chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('classroom_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], name=op.f('fk_group_chats_classroom_id_classrooms'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_group_chats_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], name=op.f('fk_group_chats_file_id_files'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_group_chats'))
    )
    op.create_index('ix_gc_classroom', 'group_chats', ['classroom_id'], unique=False)
    op.create_index('ix_gc_file_archived', 'group_chats', ['file_id', 'is_archived'], unique=False)
    op.create_table('mindmaps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('classroom_id', sa.Integer(), nullable=False),
    sa.Column('root_topic', sa.String(length=120), nullable=True),
    sa.Column('root_description', sa.Text(), nullable=True),
    sa.Column('tree_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('pending', 'generating', 'ready', 'failed', name='mindmapstatus'), nullable=False),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('node_count', sa.Integer(), nullable=False),
    sa.Column('generation_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], name=op.f('fk_mindmaps_classroom_id_classrooms'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], name=op.f('fk_mindmaps_file_id_files'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mindmaps')),
    sa.UniqueConstraint('file_id', name=op.f('uq_mindmaps_file_id'))
    )
    op.create_index('ix_mindmap_classroom_status', 'mindmaps', ['classroom_id', 'status'], unique=False)
    op.create_table('quizzes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'generating', 'ready', 'failed', 'submitted', name='quizstatus'), nullable=False),
    sa.Column('difficulty', sa.Enum('easy', 'medium', 'hard', name='quizdifficulty'), nullable=False),
    sa.Column('difficulty_source', sa.String(length=20), nullable=False),
    sa.Column('num_questions', sa.Integer(), nullable=False),
    sa.Column('questions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generation_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('ready_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('num_questions IN (5, 10, 15)', name=op.f('ck_quizzes_num_questions')),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], name=op.f('fk_quizzes_file_id_files'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_quizzes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quizzes'))
    )
    op.create_index('ix_quiz_status', 'quizzes', ['status'], unique=False)
    op.create_index('ix_quiz_user_file', 'quizzes', ['user_id', 'file_id'], unique=False)
    op.create_table('flashcards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deck_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('front', sa.Text(), nullable=False),
    sa.Column('back', sa.Text(), nullable=False),
    sa.Column('card_type', sa.Enum('definition', 'concept', 'example', 'formula', name='flashcardcardtype'), nullable=False),
    sa.Column('box', sa.Integer(), nullable=False),
    sa.Column('next_review_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deck_id'], ['flashcard_decks.id'], name=op.f('fk_flashcards_deck_id_flashcard_decks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], name=op.f('fk_flashcards_file_id_files'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_flashcards_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_flashcards'))
    )
    op.create_index('ix_card_due', 'flashcards', ['user_id', 'next_review_at'], unique=False)
    op.create_index('ix_card_user_file', 'flashcards', ['user_id', 'file_id'], unique=False)
    op.create_table('group_chat_invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_chat_id', sa.Integer(), nullable=False),
    sa.Column('inviter_id', sa.Integer(), nullable=False),
    sa.Column('invitee_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', 'expired', 'cancelled', name='invitestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_chat_id'], ['group_chats.id'], name=op.f('fk_group_chat_invites_group_chat_id_group_chats'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invitee_id'], ['users.id'], name=op.f('fk_group_chat_invites_invitee_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inviter_id'], ['users.id'], name=op.f('fk_group_chat_invites_inviter_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_group_chat_invites')),
    sa.UniqueConstraint('group_chat_id', 'invitee_id', name='uq_gc_invite_per_invitee')
    )
    op.create_table('group_chat_members',
    sa.Column('group_chat_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'member', name='grouprole'), nullable=False),
    sa.Column('joined_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_read_seq', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['group_chat_id'], ['group_chats.id'], name=op.f('fk_group_chat_members_group_chat_id_group_chats'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_group_chat_members_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_chat_id', 'user_id', name=op.f('pk_group_chat_members'))
    )
    op.create_table('group_chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_chat_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.Enum('user', 'agent', 'system', name='groupmessagerole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('mentions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reply_to_id', sa.Integer(), nullable=True),
    sa.Column('is_discarded', sa.Boolean(), nullable=False),
    sa.Column('discard_reason', sa.String(length=255), nullable=True),
    sa.Column('client_msg_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_chat_id'], ['group_chats.id'], name=op.f('fk_group_chat_messages_group_chat_id_group_chats'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reply_to_id'], ['group_chat_messages.id'], name=op.f('fk_group_chat_messages_reply_to_id_group_chat_messages'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_group_chat_messages_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_group_chat_messages')),
    sa.UniqueConstraint('group_chat_id', 'seq', name='uq_gc_message_seq')
    )
    op.create_index('ix_gcm_group_created', 'group_chat_messages', ['group_chat_id', 'created_at'], unique=False)
    op.create_index('ix_gcm_group_user', 'group_chat_messages', ['group_chat_id', 'user_id'], unique=False)
    op.create_table('mindmap_node_chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mindmap_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.String(length=64), nullable=True),
    sa.Column('role', sa.Enum('user', 'assistant', 'marker', name='mindmapmessagerole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mindmap_id'], ['mindmaps.id'], name=op.f('fk_mindmap_node_chats_mindmap_id_mindmaps'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_mindmap_node_chats_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mindmap_node_chats'))
    )
    op.create_index('ix_mindmap_chat_node', 'mindmap_node_chats', ['mindmap_id', 'user_id', 'node_id'], unique=False)
    op.create_index('ix_mindmap_chat_user_time', 'mindmap_node_chats', ['mindmap_id', 'user_id', 'created_at'], unique=False)
    op.create_table('quiz_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('answers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], name=op.f('fk_quiz_attempts_file_id_files'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], name=op.f('fk_quiz_attempts_quiz_id_quizzes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_quiz_attempts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quiz_attempts')),
    sa.UniqueConstraint('quiz_id', name=op.f('uq_quiz_attempts_quiz_id'))
    )
    op.create_index('ix_attempt_user_file', 'quiz_attempts', ['user_id', 'file_id'], unique=False)
    op.create_table('flashcard_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('result', sa.String(length=10), nullable=False),
    sa.Column('box_before', sa.Integer(), nullable=False),
    sa.Column('box_after', sa.Integer(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['flashcards.id'], name=op.f('fk_flashcard_reviews_card_id_flashcards'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_flashcard_reviews_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_flashcard_reviews'))
    )
    op.create_index('ix_review_card_user', 'flashcard_reviews', ['card_id', 'user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_review_card_user', table_name='flashcard_reviews')
    op.drop_table('flashcard_reviews')
    op.drop_index('ix_attempt_user_file', table_name='quiz_attempts')
    op.drop_table('quiz_attempts')
    op.drop_index('ix_mindmap_chat_user_time', table_name='mindmap_node_chats')
    op.drop_index('ix_mindmap_chat_node', table_name='mindmap_node_chats')
    op.drop_table('mindmap_node_chats')
    op.drop_index('ix_gcm_group_user', table_name='group_chat_messages')
    op.drop_index('ix_gcm_group_created', table_name='group_chat_messages')
    op.drop_table('group_chat_messages')
    op.drop_table('group_chat_members')
    op.drop_table('group_chat_invites')
    op.drop_index('ix_card_user_file', table_name='flashcards')
    op.drop_index('ix_card_due', table_name='flashcards')
    op.drop_table('flashcards')
    op.drop_index('ix_quiz_user_file', table_name='quizzes')
    op.drop_index('ix_quiz_status', table_name='quizzes')
    op.drop_table('quizzes')
    op.drop_index('ix_mindmap_classroom_status', table_name='mindmaps')
    op.drop_table('mindmaps')
    op.drop_index('ix_gc_file_archived', table_name='group_chats')
    op.drop_index('ix_gc_classroom', table_name='group_chats')
    op.drop_table('group_chats')
    op.drop_index('ix_deck_user_file', table_name='flashcard_decks')
    op.drop_index('ix_deck_status', table_name='flashcard_decks')
    op.drop_table('flashcard_decks')
    op.drop_index(op.f('ix_chat_messages_user_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_file_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_files_rag_doc_id'), table_name='files')
    op.drop_index(op.f('ix_files_folder_id'), table_name='files')
    op.drop_table('files')
    op.drop_index('ix_comment_announcement_id', table_name='announcement_comments')
    op.drop_table('announcement_comments')
    op.drop_index(op.f('ix_folders_classroom_id'), table_name='folders')
    op.drop_table('folders')
    op.drop_table('classroom_members')
    op.drop_index('ix_announcement_created_at', table_name='announcements')
    op.drop_index('ix_announcement_classroom_id', table_name='announcements')
    op.drop_table('announcements')
    op.drop_index(op.f('ix_classrooms_owner_id'), table_name='classrooms')
    op.drop_index(op.f('ix_classrooms_name'), table_name='classrooms')
    op.drop_index(op.f('ix_classrooms_code'), table_name='classrooms')
    op.drop_table('classrooms')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
